### ISSUE TITLE
Knit replacement function

### ISSUE THREAD

**Issue by hrbrmstr** [lecy/RMD-to-Jupyter#1]
While I'm admittedly not a fan of ipython/jupyter notbooks, having the ability to generate one from an R markdown file can only be A Very Good Thing for enabling data science folks to work together. 

To that end, I added the following function to my [`markdowntemplates`](https://github.com/hrbrmstr/markdowntemplates) package (which is not on CRAN):

```r
#' "knit" replacement to generate an ipynb with notedown
#'
#' @export
to_jupyter <- function(inputFile, encoding) {

  output_file <-  sprintf("%s.%s", tools::file_path_sans_ext(inputFile), "ipynb")

  tf <- tempfile(fileext=".Rmd")

  tmp <- readLines(inputFile)
  yaml_end <- which(grepl("^---", tmp))[2]
  writeLines(tmp[(yaml_end+1):length(tmp)], tf)

  system2("notedown", args=c(tf, "--rmagic", "--run"), stdout=output_file)

  unlink(tf)

  output_file

}
```

With that, you can then have this:

    ---
    title: "ggplot2 example"
    knit: (markdowntemplates::to_jupyter)
    ---

    ## Introduction to ggplot2

    This is a short demo on how to convert an R Markdown Notebook into an IPython Notebook using knitr and notedown.

    Adding a Python Chunk

    ```{r engine="python"}
    def f(x):
      return x + 2
    f(2)
    ```

    This is an introduction to [ggplot2](http://github.com/hadley/ggplot2). You can view the source as an R Markdown document, if you are using an IDE like RStudio, or as an IPython notebook, thanks to [notedown](https://github.com/aaren/notedown).

    We need to first make sure that we have `ggplot2` and its dependencies installed, using the `install.packages` function.

    Now that we have it installed, we can get started by loading it into our workspace

    ```{r}
    library(ggplot2)
    ```
    ... (moar R markdown code)

in an RStudio editor, use the "Knit" keystroke command or hit the "Knit" button and it will call that function (and and not call knitr's `render()`) and (since I did this in a hurry) output the filename of the rendered ipynb to the R console (you can make it do anything, like open it in a browser).

I also replaced `shell(…)` with `system2(…)` as it's cross-platform that way.

The code is totally yours to do with as you like. If you have suggestions for how the rendered ipynb shld be displayed afterwards or what messages you think would be useful during processing, just let me know.

**Comment by lecy** [comment]
Bob -

Thanks for doing this. Your solution seems simple and elegant.

My main purpose for experimenting with jupyter notebooks was to create a script that could be uploaded to a GitHub repository, and would render dynamically:

http://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/

This would basically allow you to turn a GitHub repository into an interactive website.

Unfortunately I have found the conversion between R markdown files and jupyter notebooks to be very buggy. In most cases I get strange errors, and the function is unable to produce a viable jupyter file. So I have not used this method often.

I believe this template will be helpful, though. Thanks for sharing.
